// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/promocode"
	"github.com/Wei-Shaw/sub2api/ent/promocodeusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PromoCodeUsage is the model entity for the PromoCodeUsage schema.
type PromoCodeUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 优惠码ID
	PromoCodeID int64 `json:"promo_code_id,omitempty"`
	// 使用用户ID
	UserID int64 `json:"user_id,omitempty"`
	// 订阅支付订单ID
	PaymentOrderID *int64 `json:"payment_order_id,omitempty"`
	// 用途: registration_bonus, subscription_discount
	UsageType string `json:"usage_type,omitempty"`
	// 状态: reserved, consumed, released
	Status string `json:"status,omitempty"`
	// 实际赠送金额
	BonusAmount float64 `json:"bonus_amount,omitempty"`
	// 订阅订单优惠金额
	DiscountAmount float64 `json:"discount_amount,omitempty"`
	// 使用时间
	UsedAt time.Time `json:"used_at,omitempty"`
	// ReservedAt holds the value of the "reserved_at" field.
	ReservedAt *time.Time `json:"reserved_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// ReleasedAt holds the value of the "released_at" field.
	ReleasedAt *time.Time `json:"released_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PromoCodeUsageQuery when eager-loading is set.
	Edges        PromoCodeUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PromoCodeUsageEdges holds the relations/edges for other nodes in the graph.
type PromoCodeUsageEdges struct {
	// PromoCode holds the value of the promo_code edge.
	PromoCode *PromoCode `json:"promo_code,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PromoCodeOrErr returns the PromoCode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PromoCodeUsageEdges) PromoCodeOrErr() (*PromoCode, error) {
	if e.PromoCode != nil {
		return e.PromoCode, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: promocode.Label}
	}
	return nil, &NotLoadedError{edge: "promo_code"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PromoCodeUsageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromoCodeUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promocodeusage.FieldBonusAmount, promocodeusage.FieldDiscountAmount:
			values[i] = new(sql.NullFloat64)
		case promocodeusage.FieldID, promocodeusage.FieldPromoCodeID, promocodeusage.FieldUserID, promocodeusage.FieldPaymentOrderID:
			values[i] = new(sql.NullInt64)
		case promocodeusage.FieldUsageType, promocodeusage.FieldStatus:
			values[i] = new(sql.NullString)
		case promocodeusage.FieldUsedAt, promocodeusage.FieldReservedAt, promocodeusage.FieldConsumedAt, promocodeusage.FieldReleasedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromoCodeUsage fields.
func (_m *PromoCodeUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promocodeusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case promocodeusage.FieldPromoCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field promo_code_id", values[i])
			} else if value.Valid {
				_m.PromoCodeID = value.Int64
			}
		case promocodeusage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case promocodeusage.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int64)
				*_m.PaymentOrderID = value.Int64
			}
		case promocodeusage.FieldUsageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_type", values[i])
			} else if value.Valid {
				_m.UsageType = value.String
			}
		case promocodeusage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case promocodeusage.FieldBonusAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_amount", values[i])
			} else if value.Valid {
				_m.BonusAmount = value.Float64
			}
		case promocodeusage.FieldDiscountAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_amount", values[i])
			} else if value.Valid {
				_m.DiscountAmount = value.Float64
			}
		case promocodeusage.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = value.Time
			}
		case promocodeusage.FieldReservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_at", values[i])
			} else if value.Valid {
				_m.ReservedAt = new(time.Time)
				*_m.ReservedAt = value.Time
			}
		case promocodeusage.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		case promocodeusage.FieldReleasedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field released_at", values[i])
			} else if value.Valid {
				_m.ReleasedAt = new(time.Time)
				*_m.ReleasedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromoCodeUsage.
// This includes values selected through modifiers, order, etc.
func (_m *PromoCodeUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPromoCode queries the "promo_code" edge of the PromoCodeUsage entity.
func (_m *PromoCodeUsage) QueryPromoCode() *PromoCodeQuery {
	return NewPromoCodeUsageClient(_m.config).QueryPromoCode(_m)
}

// QueryUser queries the "user" edge of the PromoCodeUsage entity.
func (_m *PromoCodeUsage) QueryUser() *UserQuery {
	return NewPromoCodeUsageClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PromoCodeUsage.
// Note that you need to call PromoCodeUsage.Unwrap() before calling this method if this PromoCodeUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromoCodeUsage) Update() *PromoCodeUsageUpdateOne {
	return NewPromoCodeUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromoCodeUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromoCodeUsage) Unwrap() *PromoCodeUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromoCodeUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromoCodeUsage) String() string {
	var builder strings.Builder
	builder.WriteString("PromoCodeUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("promo_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromoCodeID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("usage_type=")
	builder.WriteString(_m.UsageType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("bonus_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusAmount))
	builder.WriteString(", ")
	builder.WriteString("discount_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountAmount))
	builder.WriteString(", ")
	builder.WriteString("used_at=")
	builder.WriteString(_m.UsedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ReservedAt; v != nil {
		builder.WriteString("reserved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReleasedAt; v != nil {
		builder.WriteString("released_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PromoCodeUsages is a parsable slice of PromoCodeUsage.
type PromoCodeUsages []*PromoCodeUsage
