// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promocode"
	"github.com/Wei-Shaw/sub2api/ent/promocodeusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PromoCodeUsageUpdate is the builder for updating PromoCodeUsage entities.
type PromoCodeUsageUpdate struct {
	config
	hooks    []Hook
	mutation *PromoCodeUsageMutation
}

// Where appends a list predicates to the PromoCodeUsageUpdate builder.
func (_u *PromoCodeUsageUpdate) Where(ps ...predicate.PromoCodeUsage) *PromoCodeUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPromoCodeID sets the "promo_code_id" field.
func (_u *PromoCodeUsageUpdate) SetPromoCodeID(v int64) *PromoCodeUsageUpdate {
	_u.mutation.SetPromoCodeID(v)
	return _u
}

// SetNillablePromoCodeID sets the "promo_code_id" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillablePromoCodeID(v *int64) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetPromoCodeID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PromoCodeUsageUpdate) SetUserID(v int64) *PromoCodeUsageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableUserID(v *int64) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *PromoCodeUsageUpdate) SetPaymentOrderID(v int64) *PromoCodeUsageUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillablePaymentOrderID(v *int64) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *PromoCodeUsageUpdate) AddPaymentOrderID(v int64) *PromoCodeUsageUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (_u *PromoCodeUsageUpdate) ClearPaymentOrderID() *PromoCodeUsageUpdate {
	_u.mutation.ClearPaymentOrderID()
	return _u
}

// SetUsageType sets the "usage_type" field.
func (_u *PromoCodeUsageUpdate) SetUsageType(v string) *PromoCodeUsageUpdate {
	_u.mutation.SetUsageType(v)
	return _u
}

// SetNillableUsageType sets the "usage_type" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableUsageType(v *string) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetUsageType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PromoCodeUsageUpdate) SetStatus(v string) *PromoCodeUsageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableStatus(v *string) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBonusAmount sets the "bonus_amount" field.
func (_u *PromoCodeUsageUpdate) SetBonusAmount(v float64) *PromoCodeUsageUpdate {
	_u.mutation.ResetBonusAmount()
	_u.mutation.SetBonusAmount(v)
	return _u
}

// SetNillableBonusAmount sets the "bonus_amount" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableBonusAmount(v *float64) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetBonusAmount(*v)
	}
	return _u
}

// AddBonusAmount adds value to the "bonus_amount" field.
func (_u *PromoCodeUsageUpdate) AddBonusAmount(v float64) *PromoCodeUsageUpdate {
	_u.mutation.AddBonusAmount(v)
	return _u
}

// SetDiscountAmount sets the "discount_amount" field.
func (_u *PromoCodeUsageUpdate) SetDiscountAmount(v float64) *PromoCodeUsageUpdate {
	_u.mutation.ResetDiscountAmount()
	_u.mutation.SetDiscountAmount(v)
	return _u
}

// SetNillableDiscountAmount sets the "discount_amount" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableDiscountAmount(v *float64) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetDiscountAmount(*v)
	}
	return _u
}

// AddDiscountAmount adds value to the "discount_amount" field.
func (_u *PromoCodeUsageUpdate) AddDiscountAmount(v float64) *PromoCodeUsageUpdate {
	_u.mutation.AddDiscountAmount(v)
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *PromoCodeUsageUpdate) SetUsedAt(v time.Time) *PromoCodeUsageUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableUsedAt(v *time.Time) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// SetReservedAt sets the "reserved_at" field.
func (_u *PromoCodeUsageUpdate) SetReservedAt(v time.Time) *PromoCodeUsageUpdate {
	_u.mutation.SetReservedAt(v)
	return _u
}

// SetNillableReservedAt sets the "reserved_at" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableReservedAt(v *time.Time) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetReservedAt(*v)
	}
	return _u
}

// ClearReservedAt clears the value of the "reserved_at" field.
func (_u *PromoCodeUsageUpdate) ClearReservedAt() *PromoCodeUsageUpdate {
	_u.mutation.ClearReservedAt()
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *PromoCodeUsageUpdate) SetConsumedAt(v time.Time) *PromoCodeUsageUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableConsumedAt(v *time.Time) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *PromoCodeUsageUpdate) ClearConsumedAt() *PromoCodeUsageUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *PromoCodeUsageUpdate) SetReleasedAt(v time.Time) *PromoCodeUsageUpdate {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *PromoCodeUsageUpdate) SetNillableReleasedAt(v *time.Time) *PromoCodeUsageUpdate {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *PromoCodeUsageUpdate) ClearReleasedAt() *PromoCodeUsageUpdate {
	_u.mutation.ClearReleasedAt()
	return _u
}

// SetPromoCode sets the "promo_code" edge to the PromoCode entity.
func (_u *PromoCodeUsageUpdate) SetPromoCode(v *PromoCode) *PromoCodeUsageUpdate {
	return _u.SetPromoCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *PromoCodeUsageUpdate) SetUser(v *User) *PromoCodeUsageUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PromoCodeUsageMutation object of the builder.
func (_u *PromoCodeUsageUpdate) Mutation() *PromoCodeUsageMutation {
	return _u.mutation
}

// ClearPromoCode clears the "promo_code" edge to the PromoCode entity.
func (_u *PromoCodeUsageUpdate) ClearPromoCode() *PromoCodeUsageUpdate {
	_u.mutation.ClearPromoCode()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PromoCodeUsageUpdate) ClearUser() *PromoCodeUsageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromoCodeUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoCodeUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromoCodeUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoCodeUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoCodeUsageUpdate) check() error {
	if v, ok := _u.mutation.UsageType(); ok {
		if err := promocodeusage.UsageTypeValidator(v); err != nil {
			return &ValidationError{Name: "usage_type", err: fmt.Errorf(`ent: validator failed for field "PromoCodeUsage.usage_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := promocodeusage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PromoCodeUsage.status": %w`, err)}
		}
	}
	if _u.mutation.PromoCodeCleared() && len(_u.mutation.PromoCodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromoCodeUsage.promo_code"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromoCodeUsage.user"`)
	}
	return nil
}

func (_u *PromoCodeUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promocodeusage.Table, promocodeusage.Columns, sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(promocodeusage.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(promocodeusage.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentOrderIDCleared() {
		_spec.ClearField(promocodeusage.FieldPaymentOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageType(); ok {
		_spec.SetField(promocodeusage.FieldUsageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(promocodeusage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BonusAmount(); ok {
		_spec.SetField(promocodeusage.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusAmount(); ok {
		_spec.AddField(promocodeusage.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountAmount(); ok {
		_spec.SetField(promocodeusage.FieldDiscountAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountAmount(); ok {
		_spec.AddField(promocodeusage.FieldDiscountAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(promocodeusage.FieldUsedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReservedAt(); ok {
		_spec.SetField(promocodeusage.FieldReservedAt, field.TypeTime, value)
	}
	if _u.mutation.ReservedAtCleared() {
		_spec.ClearField(promocodeusage.FieldReservedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(promocodeusage.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(promocodeusage.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(promocodeusage.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(promocodeusage.FieldReleasedAt, field.TypeTime)
	}
	if _u.mutation.PromoCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promocodeusage.PromoCodeTable,
			Columns: []string{promocodeusage.PromoCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PromoCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promocodeusage.PromoCodeTable,
			Columns: []string{promocodeusage.PromoCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promocodeusage.UserTable,
			Columns: []string{promocodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promocodeusage.UserTable,
			Columns: []string{promocodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promocodeusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromoCodeUsageUpdateOne is the builder for updating a single PromoCodeUsage entity.
type PromoCodeUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromoCodeUsageMutation
}

// SetPromoCodeID sets the "promo_code_id" field.
func (_u *PromoCodeUsageUpdateOne) SetPromoCodeID(v int64) *PromoCodeUsageUpdateOne {
	_u.mutation.SetPromoCodeID(v)
	return _u
}

// SetNillablePromoCodeID sets the "promo_code_id" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillablePromoCodeID(v *int64) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetPromoCodeID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PromoCodeUsageUpdateOne) SetUserID(v int64) *PromoCodeUsageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableUserID(v *int64) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *PromoCodeUsageUpdateOne) SetPaymentOrderID(v int64) *PromoCodeUsageUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillablePaymentOrderID(v *int64) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *PromoCodeUsageUpdateOne) AddPaymentOrderID(v int64) *PromoCodeUsageUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (_u *PromoCodeUsageUpdateOne) ClearPaymentOrderID() *PromoCodeUsageUpdateOne {
	_u.mutation.ClearPaymentOrderID()
	return _u
}

// SetUsageType sets the "usage_type" field.
func (_u *PromoCodeUsageUpdateOne) SetUsageType(v string) *PromoCodeUsageUpdateOne {
	_u.mutation.SetUsageType(v)
	return _u
}

// SetNillableUsageType sets the "usage_type" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableUsageType(v *string) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetUsageType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PromoCodeUsageUpdateOne) SetStatus(v string) *PromoCodeUsageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableStatus(v *string) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBonusAmount sets the "bonus_amount" field.
func (_u *PromoCodeUsageUpdateOne) SetBonusAmount(v float64) *PromoCodeUsageUpdateOne {
	_u.mutation.ResetBonusAmount()
	_u.mutation.SetBonusAmount(v)
	return _u
}

// SetNillableBonusAmount sets the "bonus_amount" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableBonusAmount(v *float64) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetBonusAmount(*v)
	}
	return _u
}

// AddBonusAmount adds value to the "bonus_amount" field.
func (_u *PromoCodeUsageUpdateOne) AddBonusAmount(v float64) *PromoCodeUsageUpdateOne {
	_u.mutation.AddBonusAmount(v)
	return _u
}

// SetDiscountAmount sets the "discount_amount" field.
func (_u *PromoCodeUsageUpdateOne) SetDiscountAmount(v float64) *PromoCodeUsageUpdateOne {
	_u.mutation.ResetDiscountAmount()
	_u.mutation.SetDiscountAmount(v)
	return _u
}

// SetNillableDiscountAmount sets the "discount_amount" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableDiscountAmount(v *float64) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetDiscountAmount(*v)
	}
	return _u
}

// AddDiscountAmount adds value to the "discount_amount" field.
func (_u *PromoCodeUsageUpdateOne) AddDiscountAmount(v float64) *PromoCodeUsageUpdateOne {
	_u.mutation.AddDiscountAmount(v)
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *PromoCodeUsageUpdateOne) SetUsedAt(v time.Time) *PromoCodeUsageUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableUsedAt(v *time.Time) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// SetReservedAt sets the "reserved_at" field.
func (_u *PromoCodeUsageUpdateOne) SetReservedAt(v time.Time) *PromoCodeUsageUpdateOne {
	_u.mutation.SetReservedAt(v)
	return _u
}

// SetNillableReservedAt sets the "reserved_at" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableReservedAt(v *time.Time) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetReservedAt(*v)
	}
	return _u
}

// ClearReservedAt clears the value of the "reserved_at" field.
func (_u *PromoCodeUsageUpdateOne) ClearReservedAt() *PromoCodeUsageUpdateOne {
	_u.mutation.ClearReservedAt()
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *PromoCodeUsageUpdateOne) SetConsumedAt(v time.Time) *PromoCodeUsageUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableConsumedAt(v *time.Time) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *PromoCodeUsageUpdateOne) ClearConsumedAt() *PromoCodeUsageUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *PromoCodeUsageUpdateOne) SetReleasedAt(v time.Time) *PromoCodeUsageUpdateOne {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *PromoCodeUsageUpdateOne) SetNillableReleasedAt(v *time.Time) *PromoCodeUsageUpdateOne {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *PromoCodeUsageUpdateOne) ClearReleasedAt() *PromoCodeUsageUpdateOne {
	_u.mutation.ClearReleasedAt()
	return _u
}

// SetPromoCode sets the "promo_code" edge to the PromoCode entity.
func (_u *PromoCodeUsageUpdateOne) SetPromoCode(v *PromoCode) *PromoCodeUsageUpdateOne {
	return _u.SetPromoCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *PromoCodeUsageUpdateOne) SetUser(v *User) *PromoCodeUsageUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PromoCodeUsageMutation object of the builder.
func (_u *PromoCodeUsageUpdateOne) Mutation() *PromoCodeUsageMutation {
	return _u.mutation
}

// ClearPromoCode clears the "promo_code" edge to the PromoCode entity.
func (_u *PromoCodeUsageUpdateOne) ClearPromoCode() *PromoCodeUsageUpdateOne {
	_u.mutation.ClearPromoCode()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PromoCodeUsageUpdateOne) ClearUser() *PromoCodeUsageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PromoCodeUsageUpdate builder.
func (_u *PromoCodeUsageUpdateOne) Where(ps ...predicate.PromoCodeUsage) *PromoCodeUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromoCodeUsageUpdateOne) Select(field string, fields ...string) *PromoCodeUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromoCodeUsage entity.
func (_u *PromoCodeUsageUpdateOne) Save(ctx context.Context) (*PromoCodeUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromoCodeUsageUpdateOne) SaveX(ctx context.Context) *PromoCodeUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromoCodeUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromoCodeUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromoCodeUsageUpdateOne) check() error {
	if v, ok := _u.mutation.UsageType(); ok {
		if err := promocodeusage.UsageTypeValidator(v); err != nil {
			return &ValidationError{Name: "usage_type", err: fmt.Errorf(`ent: validator failed for field "PromoCodeUsage.usage_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := promocodeusage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PromoCodeUsage.status": %w`, err)}
		}
	}
	if _u.mutation.PromoCodeCleared() && len(_u.mutation.PromoCodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromoCodeUsage.promo_code"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PromoCodeUsage.user"`)
	}
	return nil
}

func (_u *PromoCodeUsageUpdateOne) sqlSave(ctx context.Context) (_node *PromoCodeUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promocodeusage.Table, promocodeusage.Columns, sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromoCodeUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promocodeusage.FieldID)
		for _, f := range fields {
			if !promocodeusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promocodeusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(promocodeusage.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(promocodeusage.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentOrderIDCleared() {
		_spec.ClearField(promocodeusage.FieldPaymentOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageType(); ok {
		_spec.SetField(promocodeusage.FieldUsageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(promocodeusage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BonusAmount(); ok {
		_spec.SetField(promocodeusage.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusAmount(); ok {
		_spec.AddField(promocodeusage.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountAmount(); ok {
		_spec.SetField(promocodeusage.FieldDiscountAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountAmount(); ok {
		_spec.AddField(promocodeusage.FieldDiscountAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(promocodeusage.FieldUsedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReservedAt(); ok {
		_spec.SetField(promocodeusage.FieldReservedAt, field.TypeTime, value)
	}
	if _u.mutation.ReservedAtCleared() {
		_spec.ClearField(promocodeusage.FieldReservedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(promocodeusage.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(promocodeusage.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(promocodeusage.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(promocodeusage.FieldReleasedAt, field.TypeTime)
	}
	if _u.mutation.PromoCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promocodeusage.PromoCodeTable,
			Columns: []string{promocodeusage.PromoCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PromoCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promocodeusage.PromoCodeTable,
			Columns: []string{promocodeusage.PromoCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promocodeusage.UserTable,
			Columns: []string{promocodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   promocodeusage.UserTable,
			Columns: []string{promocodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PromoCodeUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promocodeusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
